apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-deployment-chat
  labels:
    app: devapp-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devapp-chat
  template:
    metadata:
      labels:
        app: devapp-chat
    spec:
      containers:
      - name: nodeserver
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always